### ISSUE TITLE
oxauth remote debug is in 3.1.1 & master, but not 3.1.2 and 3.1.3

### ISSUE THREAD

**Issue by skybert** [GluuFederation/docker-oxauth#8]
Hi, 

https://github.com/GluuFederation/docker-oxauth/pull/1/commits is in 3.1.1 and `master`, but not in 3.1.2 or 3.1.3 Could you please merge it to these branches as well? We really need this feature to be present in order to work with Gluu.

-Torstein

**Comment by iromli** [comment]
Merged to `3.1.2` and `3.1.3` branch.
The `gluufederation/oxauth:3.1.2_dev` and `gluufederation/oxauth:3.1.3_dev` has been updated.

Thanks @skybert
